### ISSUE TITLE
Replication test framework should not change the agents by default

### ISSUE THREAD

**Issue by cschneider** [adobe/aem-testing-clients#11]
By default when using the ReplicationClient the url of the default publisher is changed to point to the http address of the publisher.
This might be desired for http based replication but for the cloud replication it BREAKS the replication config.

It can be switched off using:
-Dsling.it.configure.default.replication.agents=false

When running tests locally using eclipse it is very easy to forget this property. 
So I propose we change the default behaviour to not change the replication agent and either use a system property or code to enable it.

Btw. Besides the agent config the replication test support seem to break something more because even after setting the url back a cloud instance still can not do replication.

**Comment by volteanu** [comment]
the `DefaultReplicationAgents` Rule was removed in [this commit](https://github.com/adobe/aem-testing-clients/commit/f1238b2387c0e2aead4c3c1c7aa6533adb1b30dd).
