### ISSUE TITLE
Setup configurable indexing lanes (use SLING-8710)

### ISSUE THREAD

**Issue by catholicon** [adobe/aem-testing-clients#18]
SLING-8710 added a functionality to configure hard coded indexing lanes to `IndexingClient` so that waiting on indexing cycle to be completed without accessing /system/console.

Doing this is useful as we'd want to avoid reaching into /system/console just to get indexing lanes - which isn't a very dynamic property anyway.

**Comment by catholicon** [comment]
Please note that this issue can only be resolved only after sling-testing-clients version containing fix for SLING-8710 is already included.

**Comment by catholicon** [comment]
While discussing this with @volteanu, he mentioned that such a feature (reading system prop and initializing a config for a client, etc) is better suited to be done in `rules` such as [ClassRuleUtil](https://github.com/adobe/aem-testing-clients/blob/cq-65/src/main/java/com/adobe/cq/testing/junit/rules/ClassRuleUtils.java)

**Comment by catholicon** [comment]
@volteanu I've committed catholicon/aem-testing-clients@49ffa7b in my fork. This is the same change that I had shared with you earlier. I couldn't wrap my head around doing things in rules. Could you please help me a bit?

**Comment by volteanu** [comment]
Sorry for the delay. I've commented on the commit how I think it should be handled in the rules. Let me know if it's not clear :)

**Comment by catholicon** [comment]
@volteanu, sling testing clients 1.2.4 has been released. Can you please bump that - I'd open a PR for this issue after that (please ping me once you've bumped it)

#inothernews, I've tried to incorporate review comments in catholicon/aem-testing-clients@e1fb171

**Comment by volteanu** [comment]
> sling testing clients 1.2.4 has been released. Can you please bump that

Done: https://github.com/adobe/aem-testing-clients/commit/404b178050a61f5e19acd18651e83c1046b67a9c

@catholicon can you please create the PR so we easily track the feedback?

**Comment by dulvac** [comment]
@catholicon, @volteanu , can we get this sorted out?

**Comment by volteanu** [comment]
thanks @catholicon ! I've merged the PR and released `cq-testing-clients-65-1.0.2`. It should be available in maven central soon, so you can start using it.
