### ISSUE TITLE
Since SLING-8921 lot of client that uses doGet and directly passes parameters are now failing with 404

### ISSUE THREAD

**Issue by tyge68** [adobe/aem-testing-clients#27]
Due to recent change SLING-8921 which change how AbstractSlingClient.getUrl(path) is computed now lot of clients which still directly add parameters in the path not using the List of params are now resulting in 404.

That mainly impact projects that upgraded to latest sling testing client (for the 503 retries improvement). Also this impact many projects that are running on top of aem testing client.

Example https://github.com/adobe/aem-testing-clients/blob/aem-cloud/src/main/java/com/adobe/cq/testing/client/JsonClient.java#L59

**Comment by volteanu** [comment]
@tyge68 I think your fix solved this. Let me know if I should re-open it.
