### ISSUE TITLE
Feature Request: UserRule

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-testing-clients#49]
There should be a class rule, which creates a user and makes it a member of configurable groups and adds a random password. These groups must exist already on the system before this rule is invoked.
Then it should be possible to use the credentials for that user in any client.

With this in place tests can be executed more easily against AEM using a regular user. This allows to test more cases, especially when it comes to permissions.

**Comment by volteanu** [comment]
@joerghoh this was added in #54
